#pragma once

// from glfw3.h

#define MEMOGL_JOYSTICK_1             0
#define MEMOGL_JOYSTICK_2             1
#define MEMOGL_JOYSTICK_3             2
#define MEMOGL_JOYSTICK_4             3
#define MEMOGL_JOYSTICK_5             4
#define MEMOGL_JOYSTICK_6             5
#define MEMOGL_JOYSTICK_7             6
#define MEMOGL_JOYSTICK_8             7
#define MEMOGL_JOYSTICK_9             8
#define MEMOGL_JOYSTICK_10            9
#define MEMOGL_JOYSTICK_11            10
#define MEMOGL_JOYSTICK_12            11
#define MEMOGL_JOYSTICK_13            12
#define MEMOGL_JOYSTICK_14            13
#define MEMOGL_JOYSTICK_15            14
#define MEMOGL_JOYSTICK_16            15
#define MEMOGL_JOYSTICK_LAST          MEMOGL_JOYSTICK_16


#define MEMOGL_GAMEPAD_BUTTON_A               0
#define MEMOGL_GAMEPAD_BUTTON_B               1
#define MEMOGL_GAMEPAD_BUTTON_X               2
#define MEMOGL_GAMEPAD_BUTTON_Y               3
#define MEMOGL_GAMEPAD_BUTTON_LEFT_BUMPER     4
#define MEMOGL_GAMEPAD_BUTTON_RIGHT_BUMPER    5
#define MEMOGL_GAMEPAD_BUTTON_BACK            6
#define MEMOGL_GAMEPAD_BUTTON_START           7
#define MEMOGL_GAMEPAD_BUTTON_GUIDE           8
#define MEMOGL_GAMEPAD_BUTTON_LEFT_THUMB      9
#define MEMOGL_GAMEPAD_BUTTON_RIGHT_THUMB     10
#define MEMOGL_GAMEPAD_BUTTON_DPAD_UP         11
#define MEMOGL_GAMEPAD_BUTTON_DPAD_RIGHT      12
#define MEMOGL_GAMEPAD_BUTTON_DPAD_DOWN       13
#define MEMOGL_GAMEPAD_BUTTON_DPAD_LEFT       14
#define MEMOGL_GAMEPAD_BUTTON_LAST            MEMOGL_GAMEPAD_BUTTON_DPAD_LEFT


#define MEMOGL_GAMEPAD_BUTTON_CROSS       MEMOGL_GAMEPAD_BUTTON_A
#define MEMOGL_GAMEPAD_BUTTON_CIRCLE      MEMOGL_GAMEPAD_BUTTON_B
#define MEMOGL_GAMEPAD_BUTTON_SQUARE      MEMOGL_GAMEPAD_BUTTON_X
#define MEMOGL_GAMEPAD_BUTTON_TRIANGLE    MEMOGL_GAMEPAD_BUTTON_Y


#define MEMOGL_GAMEPAD_AXIS_LEFT_X        0
#define MEMOGL_GAMEPAD_AXIS_LEFT_Y        1
#define MEMOGL_GAMEPAD_AXIS_RIGHT_X       2
#define MEMOGL_GAMEPAD_AXIS_RIGHT_Y       3
#define MEMOGL_GAMEPAD_AXIS_LEFT_TRIGGER  4
#define MEMOGL_GAMEPAD_AXIS_RIGHT_TRIGGER 5
#define MEMOGL_GAMEPAD_AXIS_LAST          MEMOGL_GAMEPAD_AXIS_RIGHT_TRIGGER