#pragma once

//from glfw3.h

#define MEMOGL_MOUSE_BUTTON_1         0
#define MEMOGL_MOUSE_BUTTON_2         1
#define MEMOGL_MOUSE_BUTTON_3         2
#define MEMOGL_MOUSE_BUTTON_4         3
#define MEMOGL_MOUSE_BUTTON_5         4
#define MEMOGL_MOUSE_BUTTON_6         5
#define MEMOGL_MOUSE_BUTTON_7         6
#define MEMOGL_MOUSE_BUTTON_8         7
#define MEMOGL_MOUSE_BUTTON_LAST      MEMOGL_MOUSE_BUTTON_8
#define MEMOGL_MOUSE_BUTTON_LEFT      MEMOGL_MOUSE_BUTTON_1
#define MEMOGL_MOUSE_BUTTON_RIGHT     MEMOGL_MOUSE_BUTTON_2
#define MEMOGL_MOUSE_BUTTON_MIDDLE    MEMOGL_MOUSE_BUTTON_3
